### ISSUE TITLE
Carthage: cannot use Sentiance

### ISSUE THREAD

**Issue by mikeger** [sentiance/sentsdk-package#1]
When using Carthage:

```
*** Downloading binary-only framework SENTSDK at "https://sentiance-u1-sdk-downloads.s3-eu-west-1.amazonaws.com/ios/carthage/SENTSDK.json"
*** Downloading binary-only framework FirebaseMessagingBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseMessagingBinary.json"
Unable to parse binary-only framework JSON at https://sentiance-u1-sdk-downloads.s3-eu-west-1.amazonaws.com/ios/carthage/SENTSDK.json due to error: unable to parse semantic version: Build metadata contains invalid characters, in "6.9.0"
```

I assume Carthage cannot understand keys that have versions different from a classic SEMVER format with several number groups separated with dots, i.e. versions like 6.2.0-rc4

**Comment by sebouh00** [comment]
Thanks for reporting. We've addressed the issue.

Note that this repo is the Sentiance SDK's Swift package. For other types of integration issues, you can always reach out to us via our support email address.

**Comment by mikeger** [comment]
Thanks @sebouh00 , I confirm it's resolved now
